Write-Output `n "===========================  Windows Feature Installation  ===========================" `n

Install-WindowsFeature Server-Media-Foundation
Install-WindowsFeature NET-Framework-45-Features
Install-WindowsFeature RPC-over-HTTP-proxy
Install-WindowsFeature RSAT-Clustering
Install-WindowsFeature RSAT-Clustering-CmdInterface
Install-WindowsFeature RSAT-Clustering-Mgmt
Install-WindowsFeature RSAT-Clustering-PowerShell
Install-WindowsFeature WAS-Process-Model
Install-WindowsFeature Web-Asp-Net45
Install-WindowsFeature Web-Basic-Auth
Install-WindowsFeature Web-Client-Auth
Install-WindowsFeature Web-Digest-Auth
Install-WindowsFeature Web-Dir-Browsing
Install-WindowsFeature Web-Dyn-Compression
Install-WindowsFeature Web-Http-Errors
Install-WindowsFeature Web-Http-Logging
Install-WindowsFeature Web-Http-Redirect
Install-WindowsFeature Web-Http-Tracing
Install-WindowsFeature Web-ISAPI-Ext
Install-WindowsFeature Web-ISAPI-Filter
Install-WindowsFeature Web-Lgcy-Mgmt-Console
Install-WindowsFeature Web-Metabase
Install-WindowsFeature Web-Mgmt-Console
Install-WindowsFeature Web-Mgmt-Service
Install-WindowsFeature Web-Net-Ext45
Install-WindowsFeature Web-Request-Monitor
Install-WindowsFeature Web-Server
Install-WindowsFeature Web-Stat-Compression
Install-WindowsFeature Web-Static-Content
Install-WindowsFeature Web-Windows-Auth
Install-WindowsFeature Web-WMI
Install-WindowsFeature Windows-Identity-Foundation
Install-WindowsFeature RSAT-ADDS